# Generated by Django 5.0.3 on 2024-06-10 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('source_of_lead', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('joining_centre', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('education_background', models.CharField(max_length=50)),
                ('main', models.TextField(blank=True, null=True)),
                ('cs_background', models.CharField(max_length=3)),
                ('employed', models.BooleanField()),
                ('joining_month', models.CharField(max_length=20)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('initial_response', models.TextField(blank=True, null=True)),
                ('first_follow_up', models.TextField(blank=True, null=True)),
                ('first_follow_up_date', models.DateField(blank=True, null=True)),
                ('second_follow_up', models.TextField(blank=True, null=True)),
                ('second_follow_up_date', models.DateField(blank=True, null=True)),
                ('third_follow_up', models.TextField(blank=True, null=True)),
                ('third_follow_up_date', models.DateField(blank=True, null=True)),
                ('counsellor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
