# Generated by Django 5.0.3 on 2024-06-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_counsellor_photo_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
