# Generated by Django 5.0.3 on 2024-06-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_counsellor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='status',
            field=models.CharField(default='active', max_length=355),
        ),
    ]
