# Generated by Django 5.0.3 on 2024-06-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_counsellor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
