# Generated by Django 5.0.3 on 2024-06-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_counsellor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
