# Generated by Django 5.0.3 on 2024-06-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_login_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_details',
            name='browser',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='login_details',
            name='browser_version',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='login_details',
            name='is_bot',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='login_details',
            name='is_mobile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='login_details',
            name='is_pc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='login_details',
            name='is_tablet',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='login_details',
            name='os',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='login_details',
            name='os_version',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
