# Generated by Django 5.0.3 on 2024-06-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_login_details_browser_login_details_browser_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_details',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='login_details',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='login_details',
            name='is_pc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='login_details',
            name='is_tablet',
            field=models.BooleanField(default=False),
        ),
    ]
