# Generated by Django 5.0.3 on 2024-06-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_login_details_is_bot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='additional_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_follow_up',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_follow_up_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='initial_response',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='second_follow_up',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='second_follow_up_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='third_follow_up',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='third_follow_up_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
