# Generated by Django 5.0.3 on 2024-06-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_lead_additional_notes_alter_lead_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='cs_background',
            field=models.BooleanField(default=True),
        ),
    ]
