# Generated by Django 5.0.3 on 2024-06-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
