# Generated by Django 5.0.3 on 2024-06-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_notifications_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
