# Generated by Django 5.0.3 on 2024-06-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_notifications_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
